name: linux-conquest # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Client for the online multiplayer game Conquest
description: |
  This is a client for the online multiplayer action game Conquest

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon: Klingon.png
title: Conquest

apps:
  conquest:
    command: bin/conquest
parts:
  conquest:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
    build-packages: [libsdl2-dev, libsdl2-mixer-dev, ncurses-dev, freeglut3-dev, libxi-dev, libxmu-dev]
    stage-packages: [libsdl2-dev, libsdl2-mixer-dev, ncurses-dev, freeglut3-dev, libxi-dev, libxmu-dev]
    organize:
      conquest: bin/
      conquest.1: man/man1/

architectures:
  - build-on: amd64

